# Map untuk upgrade WebSocket
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

map $http_x_forwarded_proto $forwarded_proto {
    default $scheme;
    "https" https;
    "http" http;
}
